# ruby encoding: utf-8

@meldeliste = Boxer.create!([
  
{ first_name: '	Corinna 	', last_name: ' 	Schmechel	', date_of_birth: Date.parse('	1987-01-01	'), weight:	57	, gender:	TRUE	, fights_won:	10	, fights_lost:	12	, fights_drawn:	1	, club_id:	2	},
{ first_name: '	Franciska	', last_name: ' 	Krenn	', date_of_birth: Date.parse('	1987-01-01	'), weight:	87	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Sarah	', last_name: ' 	Krocker	', date_of_birth: Date.parse('	1991-05-01	'), weight:	63	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Pascal	', last_name: ' 	Kratzke	', date_of_birth: Date.parse('	2003-12-01	'), weight:	31	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Nico	', last_name: ' 	Neumann	', date_of_birth: Date.parse('	2003-07-01	'), weight:	41	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Karl-Georg	', last_name: ' 	Maruschke	', date_of_birth: Date.parse('	1999-11-01	'), weight:	53	, gender:	FALSE	, fights_won:	3	, fights_lost:	1	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Kevin	', last_name: ' 	Enkhtungalag	', date_of_birth: Date.parse('	1999-02-01	'), weight:	54	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Andy	', last_name: ' 	Wuzosok	', date_of_birth: Date.parse('	1998-02-01	'), weight:	64	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Arthur	', last_name: ' 	Glück	', date_of_birth: Date.parse('	1996-07-01	'), weight:	68	, gender:	FALSE	, fights_won:	5	, fights_lost:	4	, fights_drawn:	1	, club_id:	2	},
{ first_name: '	Hans	', last_name: ' 	Sachs	', date_of_birth: Date.parse('	1996-05-01	'), weight:	84	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Jonas	', last_name: ' 	Werner	', date_of_birth: Date.parse('	1992-03-01	'), weight:	66	, gender:	FALSE	, fights_won:	0	, fights_lost:	1	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Andre	', last_name: ' 	Lakisov	', date_of_birth: Date.parse('	1983-07-01	'), weight:	66	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	1	, club_id:	2	},
{ first_name: '	Karsten	', last_name: ' 	Lutzke	', date_of_birth: Date.parse('	1982-09-01	'), weight:	69	, gender:	FALSE	, fights_won:	1	, fights_lost:	1	, fights_drawn:	0	, club_id:	2	},
{ first_name: '	Paul	', last_name: ' 	Respondek	', date_of_birth: Date.parse('	1994-04-01	'), weight:	83	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	2	},
																		
																		
#{ first_name: '	Julian	', last_name: ' 	Campo	', date_of_birth: Date.parse('	2003-01-01	'), weight:	29	, gender:	FALSE	, fights_won:	6	, fights_lost:	1	, fights_drawn:	0	, club_id:	6	},
#{ first_name: '	Delijan	', last_name: ' 	Krause	', date_of_birth: Date.parse('	2003-08-01	'), weight:	30	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	6	},
#{ first_name: '	Angelo	', last_name: ' 	Campo	', date_of_birth: Date.parse('	2000-09-01	'), weight:	35	, gender:	FALSE	, fights_won:	8	, fights_lost:	5	, fights_drawn:	1	, club_id:	6	},
#{ first_name: '	Felix	', last_name: ' 	Kuhrt	', date_of_birth: Date.parse('	2000-06-01	'), weight:	38, gender:	FALSE	, fights_won: 4 , fights_lost:	1	, fights_drawn:	0	, club_id:	6	},
#{ first_name: '	Toni	', last_name: ' 	Marx	', date_of_birth: Date.parse('	2000-09-01	'), weight:	66	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	6	},
#{ first_name: '	Luis	', last_name: ' 	Campo	', date_of_birth: Date.parse('	1998-04-01	'), weight:	58	, gender:	FALSE	, fights_won:	0	, fights_lost:	1	, fights_drawn:	0	, club_id:	6	},
#{ first_name: '	Ilja	', last_name: ' 	Lejkam	', date_of_birth: Date.parse('	1998-08-01	'), weight:	70	, gender:	FALSE	, fights_won:	1	, fights_lost:	0	, fights_drawn:	0	, club_id:	6	},
#{ first_name: '	Eric	', last_name: ' 	Ritzmann	', date_of_birth: Date.parse('	1987-11-01	'), weight:	66	, gender:	FALSE	, fights_won:	4	, fights_lost:	3	, fights_drawn:	0	, club_id:	6	},
#{ first_name: '	Mario	', last_name: ' 	Campo	', date_of_birth: Date.parse('	1993-09-01	'), weight:	73	, gender:	FALSE	, fights_won:	27	, fights_lost:	18	, fights_drawn:	6	, club_id:	6	},
																		
																		
#{ first_name: '	Maurice	', last_name: ' 	Barth	', date_of_birth: Date.parse('	2005-06-01	'), weight:	36	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	7	},
#{ first_name: '	Leon	', last_name: ' 	Spyrantis	', date_of_birth: Date.parse('	2001-06-01	'), weight:	41	, gender:	FALSE	, fights_won:	1	, fights_lost:	0 	, fights_drawn:	0	, club_id:	7	},
#{ first_name: '	Rocky	', last_name: ' 	Fuhr	', date_of_birth: Date.parse('	2001-12-01	'), weight:	51	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	7	},
#{ first_name: '	Tim	', last_name: ' 	Hoffmann	', date_of_birth: Date.parse('	2002-05-01	'), weight:	54	, gender:	FALSE	, fights_won:	1	, fights_lost:	0	, fights_drawn:	0	, club_id:	7	},
#{ first_name: '	George	', last_name: ' 	Skeide	', date_of_birth: Date.parse('	1999-12-01	'), weight:	69	, gender:	FALSE	, fights_won:	3	, fights_lost:	5	, fights_drawn:	0	, club_id:	7	},
#{ first_name: '	Rustam	', last_name: ' 	Yasnowskyy	', date_of_birth: Date.parse('	1999-07-01	'), weight:	96	, gender:	FALSE	, fights_won:	0	, fights_lost:	2	, fights_drawn:	0	, club_id:	7	},
#{ first_name: '	Daniel	', last_name: ' 	Jaß	', date_of_birth: Date.parse('	1991-11-01	'), weight:	64	, gender:	FALSE	, fights_won:	42	, fights_lost:	35	, fights_drawn:	3	, club_id:	7	},
																		
{ first_name: '	Joelle	', last_name: ' 	Seydou	', date_of_birth: Date.parse('	1995-11-01	'), weight:	66 ,	gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	1	, club_id:	8	},
{ first_name: '	Natalie	', last_name: ' 	Ramm	', date_of_birth: Date.parse('	1990-01-01	'), weight:	62	, gender:	TRUE	, fights_won:	10	, fights_lost:	11	, fights_drawn:	3	, club_id:	8	},
{ first_name: '	Celine	', last_name: ' 	Naderipour	', date_of_birth: Date.parse('	1981-04-01	'), weight:	51	, gender:	TRUE	, fights_won:	1	, fights_lost:	2	, fights_drawn:	0	, club_id:	8	},
{ first_name: '	Nele	', last_name: ' 	Rades	', date_of_birth: Date.parse('	1981-06-01	'), weight:	59	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	1	, club_id:	8	},
																		
{ first_name: '	Simon	', last_name: ' 	Rieth	', date_of_birth: Date.parse('	2003-09-01	'), weight:	32	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	8	},
{ first_name: '	Santino	', last_name: ' 	Franke	', date_of_birth: Date.parse('	2003-12-01	'), weight:	37	, gender:	FALSE	, fights_won:	1	, fights_lost:	0	, fights_drawn:	0	, club_id:	8	},
{ first_name: '	Oruc	', last_name: ' 	Özer	', date_of_birth: Date.parse('	2000-01-01	'), weight:	47	, gender:	FALSE	, fights_won:	13	, fights_lost:	11	, fights_drawn:	1	, club_id:	8	},
{ first_name: '	Yasef	', last_name: ' 	Koyuncu	', date_of_birth: Date.parse('	1999-06-01	'), weight:	63	, gender:	FALSE	, fights_won:	1	, fights_lost:	3	, fights_drawn:	0	, club_id:	8	},
{ first_name: '	Ibrahim	', last_name: ' 	Bazuev	', date_of_birth: Date.parse('	1994-01-01	'), weight:	83	, gender:	FALSE	, fights_won:	44	, fights_lost:	3	, fights_drawn:	15	, club_id:	8	},
																		
{ first_name: '	Tim	', last_name: ' 	Wildemann	', date_of_birth: Date.parse('	1999-05-01	'), weight:	56	, gender:	FALSE	, fights_won:	4	, fights_lost:	5	, fights_drawn:	1	, club_id:	9	},
{ first_name: '	Konstantin	', last_name: ' 	Haase	', date_of_birth: Date.parse('	1999-05-01	'), weight:	58	, gender:	FALSE	, fights_won:	2	, fights_lost:	6	, fights_drawn:	0	, club_id:	9	},
{ first_name: '	Pascal	', last_name: ' 	Braun	', date_of_birth: Date.parse('	1998-04-01	'), weight:	57	, gender:	FALSE	, fights_won:	5	, fights_lost:	5	, fights_drawn:	0	, club_id:	9	},
{ first_name: '	Patrick	', last_name: ' 	Harbeck	', date_of_birth: Date.parse('	1998-03-01	'), weight:	81	, gender:	FALSE	, fights_won:	4	, fights_lost:	4	, fights_drawn:	0	, club_id:	9	},
{ first_name: '	Muhammed	', last_name: ' 	Uludogan	', date_of_birth: Date.parse('	1997-07-01	'), weight:	86 , gender:	FALSE	, fights_won:	2	, fights_lost:	0	, fights_drawn:	0	, club_id:	9	},
{ first_name: '	Darian	', last_name: ' 	Neumann	', date_of_birth: Date.parse('	1990-07-01	'), weight:	69	, gender:	FALSE	, fights_won:	29	, fights_lost:	18	, fights_drawn:	7	, club_id:	9	},
																		
{ first_name: '	Lotte	', last_name: ' 	Knold-Andersen	', date_of_birth: Date.parse('	1990-07-01	'), weight:	59.8	, gender:	TRUE	, fights_won:	1	, fights_lost:	0	, fights_drawn:	0	, club_id:	10	},
{ first_name: '	Helena	', last_name: ' 	Mihaljevic-Brandt	', date_of_birth: Date.parse('	1990-07-01	'), weight:	62	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	10	},
																		
{ first_name: '	Georg	', last_name: ' 	Wolf	', date_of_birth: Date.parse('	1999-09-01	'), weight:	59.4	, gender:	FALSE	, fights_won:	7	, fights_lost:	3	, fights_drawn:	0	, club_id:	11	},
{ first_name: '	Vladimir	', last_name: ' 	Bekler	', date_of_birth: Date.parse('	1994-04-01	'), weight:	74.6	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	11	},
{ first_name: '	Mamaa	', last_name: ' 	Diallo	', date_of_birth: Date.parse('	1982-07-01	'), weight:	76.8	, gender:	FALSE	, fights_won:	10	, fights_lost:	5	, fights_drawn:	1	, club_id:	11	},
																		
{ first_name: '	Elisa	', last_name: ' 	Rohde	', date_of_birth: Date.parse('	2000-08-01	'), weight:	45.5	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	12	},
{ first_name: '	Steffen	', last_name: ' 	Bischoff	', date_of_birth: Date.parse('	1999-07-01	'), weight:	52	, gender:	FALSE	, fights_won:	3	, fights_lost:	0	, fights_drawn:	0	, club_id:	12	},
#{ first_name: '	Eric	', last_name: ' 	Rohde	', date_of_birth: Date.parse('	2003-07-01	'), weight:	29	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	12	},
#{ first_name: '	Stepahn	', last_name: ' 	Wohlfahrt	', date_of_birth: Date.parse('	1989-08-01	'), weight:	70	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	12	},
																		
{ first_name: '	Malik	', last_name: ' 	Shadalov	', date_of_birth: Date.parse('	2003-05-01	'), weight:	25	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Björn	', last_name: ' 	Hiller	', date_of_birth: Date.parse('	2002-03-01	'), weight:	52	, gender:	FALSE	, fights_won:	3	, fights_lost:	2	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Arbi	', last_name: ' 	Misaev	', date_of_birth: Date.parse('	2001-10-01	'), weight:	36	, gender:	FALSE	, fights_won:	2	, fights_lost:	2	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Alex	', last_name: ' 	Snegirev	', date_of_birth: Date.parse('	2001-12-01	'), weight:	52	, gender:	FALSE	, fights_won:	6	, fights_lost:	2	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Jan	', last_name: ' 	Nefedov	', date_of_birth: Date.parse('	2001-02-01	'), weight:	51	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Abdukarim	', last_name: ' 	Artschakov	', date_of_birth: Date.parse('	1999-12-01	'), weight:	40	, gender:	FALSE	, fights_won:	4	, fights_lost:	1	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Deni	', last_name: ' 	Misaev	', date_of_birth: Date.parse('	2000-05-01	'), weight:	46	, gender:	FALSE	, fights_won:	1	, fights_lost:	1	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Joey	', last_name: ' 	Hachulla	', date_of_birth: Date.parse('	1999-07-01	'), weight:	56	, gender:	FALSE	, fights_won:	5	, fights_lost:	1	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Ibragim	', last_name: ' 	Achmedov	', date_of_birth: Date.parse('	1999-07-01	'), weight:	57	, gender:	FALSE	, fights_won:	0	, fights_lost:	2	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Hamsat	', last_name: ' 	Shadalov	', date_of_birth: Date.parse('	1998-10-01	'), weight:	40	, gender:	FALSE	, fights_won:	25	, fights_lost:	2	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Tobias	', last_name: ' 	Michel	', date_of_birth: Date.parse('	1998-11-01	'), weight:	47	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Samat	', last_name: ' 	Machmudov	', date_of_birth: Date.parse('	1998-04-01	'), weight:	57	, gender:	FALSE	, fights_won:	22	, fights_lost:	15	, fights_drawn:	2	, club_id:	13	},
{ first_name: '	Nicolaj	', last_name: ' 	Terguta	', date_of_birth: Date.parse('	1998-03-01	'), weight:	60	, gender:	FALSE	, fights_won:	3	, fights_lost:	3	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Sulimanov	', last_name: ' 	Zelimkha	', date_of_birth: Date.parse('	1998-01-01	'), weight:	60	, gender:	FALSE	, fights_won:	6	, fights_lost:	5	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Vanessa	', last_name: ' 	Mertens	', date_of_birth: Date.parse('	1997-07-01	'), weight:	62	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Dadaev	', last_name: ' 	Khamzak	', date_of_birth: Date.parse('	1997-04-01	'), weight:	81	, gender:	FALSE	, fights_won:	1	, fights_lost:	1	, fights_drawn:	1	, club_id:	13	},
{ first_name: '	Leard	', last_name: ' 	Brigert	', date_of_birth: Date.parse('	1996-11-01	'), weight:	61	, gender:	FALSE	, fights_won:	0	, fights_lost:	1	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Abdurahman	', last_name: ' 	Artschakov	', date_of_birth: Date.parse('	1996-06-01	'), weight:	64	, gender:	FALSE	, fights_won:	1	, fights_lost:	0	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Umarhan	', last_name: ' 	Ahmatsultanov	', date_of_birth: Date.parse('	1995-10-01	'), weight:	70	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Zeynal	', last_name: ' 	Veliev	', date_of_birth: Date.parse('	1989-09-01	'), weight:	61	, gender:	FALSE	, fights_won:	1	, fights_lost:	2	, fights_drawn:	0	, club_id:	13	},
{ first_name: '	Nikolay	', last_name: ' 	Zadishvili	', date_of_birth: Date.parse('	1992-06-01	'), weight:	73	, gender:	FALSE	, fights_won:	12	, fights_lost:	12	, fights_drawn:	0	, club_id:	13	},
#{ first_name: '	Mansur	', last_name: ' 	Shukulov	', date_of_birth: Date.parse('	1990-04-01	'), weight:	85	, gender:	FALSE	, fights_won:	7	, fights_lost:	3	, fights_drawn:	1	, club_id:	13	},
																		
#{ first_name: '	Benjamin	', last_name: ' 	Bechly	', date_of_birth: Date.parse('	2001-06-01	'), weight:	42	, gender:	FALSE	, fights_won:	0	, fights_lost:	3	, fights_drawn:	0	, club_id:	14	},
#{ first_name: '	Niklas	', last_name: ' 	Krierke	', date_of_birth: Date.parse('	2000-12-01	'), weight:	52	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	14	},
#{ first_name: '	Matthias	', last_name: ' 	Blank	', date_of_birth: Date.parse('	1996-01-01	'), weight:	75	, gender:	FALSE	, fights_won:	0	, fights_lost:	1	, fights_drawn:	0	, club_id:	14	},
#{ first_name: '	Hussein	', last_name: ' 	Hassanzadeh	', date_of_birth: Date.parse('	1995-01-01	'), weight:	58	, gender:	FALSE	, fights_won:	0	, fights_lost:	1	, fights_drawn:	0	, club_id:	14	},
#{ first_name: '	Martin	', last_name: ' 	Schulz	', date_of_birth: Date.parse('	1993-01-01	'), weight:	75	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	14	},
#{ first_name: '	Pilipp	', last_name: ' 	Hensel	', date_of_birth: Date.parse('	1991-01-01	'), weight:	81	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	14	},
#{ first_name: '	Danilo	', last_name: ' 	Rosendahl	', date_of_birth: Date.parse('	1986-01-01	'), weight:	91	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	14	},
																		
#{ first_name: '	Laura	', last_name: ' 	Kimpel	', date_of_birth: Date.parse('	1993-01-01	'), weight:	57.5	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	15	},
{ first_name: '	Semih	', last_name: ' 	Öztürk	', date_of_birth: Date.parse('	1998-10-01	'), weight:	50	, gender:	FALSE	, fights_won:	15	, fights_lost:	13	, fights_drawn:	1	, club_id:	15	},
{ first_name: '	Ayaz	', last_name: ' 	Aloskan	', date_of_birth: Date.parse('	1997-01-01	'), weight:	55	, gender:	FALSE	, fights_won:	1	, fights_lost:	1	, fights_drawn:	0	, club_id:	15	},
{ first_name: '	Metin	', last_name: ' 	Sükmen	', date_of_birth: Date.parse('	1997-11-01	'), weight:	59.5	, gender:	FALSE	, fights_won:	24	, fights_lost:	14	, fights_drawn:	2	, club_id:	15	},
{ first_name: '	Volkan	', last_name: ' 	Özdemir	', date_of_birth: Date.parse('	1998-04-01	'), weight:	73	, gender:	FALSE	, fights_won:	1	, fights_lost:	2	, fights_drawn:	0	, club_id:	15	},
{ first_name: '	Tarek	', last_name: ' 	Baish	', date_of_birth: Date.parse('	1983-03-01	'), weight:	75.5	, gender:	FALSE	, fights_won:	4	, fights_lost:	3	, fights_drawn:	0	, club_id:	15	},
																		
{ first_name: '	Hamza	', last_name: ' 	Katciev	', date_of_birth: Date.parse('	2003-03-01	'), weight:	32	, gender:	FALSE	, fights_won:	4	, fights_lost:	4	, fights_drawn:	0	, club_id:	16	},
#{ first_name: '	Fabio	', last_name: ' 	Martins	', date_of_birth: Date.parse('	2001-03-01	'), weight:	55	, gender:	FALSE	, fights_won:	2	, fights_lost:	3	, fights_drawn:	0	, club_id:	16	},
{ first_name: '	Fabian	', last_name: ' 	Thiemke	', date_of_birth: Date.parse('	2000-06-01	'), weight:	65	, gender:	FALSE	, fights_won:	17	, fights_lost:	7	, fights_drawn:	0	, club_id:	16	},
{ first_name: '	Flamur	', last_name: ' 	Tahiri	', date_of_birth: Date.parse('	1999-06-01	'), weight:	60	, gender:	FALSE	, fights_won:	6	, fights_lost:	1	, fights_drawn:	0	, club_id:	16	},
{ first_name: '	Khashayar	', last_name: ' 	Abbasi	', date_of_birth: Date.parse('	1999-03-01	'), weight:	71	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	16	},
{ first_name: '	Sebastian	', last_name: ' 	Schaub	', date_of_birth: Date.parse('	1995-08-01	'), weight:	58	, gender:	FALSE	, fights_won:	4	, fights_lost:	2	, fights_drawn:	1	, club_id:	16	},
																		
{ first_name: '	Carlos	', last_name: ' 	font Salazav	', date_of_birth: Date.parse('	1996-02-01	'), weight:	65	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	17	},
																		
{ first_name: '	Sascha	', last_name: ' 	Steger	', date_of_birth: Date.parse('	1992-04-01	'), weight:	69	, gender:	FALSE	, fights_won:	0	, fights_lost:	3	, fights_drawn:	0	, club_id:	18	},
{ first_name: '	T.Gerit	', last_name: ' 	Schult	', date_of_birth: Date.parse('	1988-07-01	'), weight:	81	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	18	},
{ first_name: '	Martin	', last_name: ' 	Walla	', date_of_birth: Date.parse('	1991-09-01	'), weight:	81	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	18	},
{ first_name: '	Frederik	', last_name: ' 	Franz	', date_of_birth: Date.parse('	1990-08-01	'), weight:	81	, gender:	FALSE	, fights_won:	7	, fights_lost:	4	, fights_drawn:	1	, club_id:	18	},
{ first_name: '	Michael	', last_name: ' 	Hoffmann	', date_of_birth: Date.parse('	1988-04-01	'), weight:	91	, gender:	FALSE	, fights_won:	1	, fights_lost:	1	, fights_drawn:	0	, club_id:	18	},
{ first_name: '	Gesche	', last_name: ' 	Boedecker	', date_of_birth: Date.parse('	1974-01-01	'), weight:	71	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	18	},
																		
																		
{ first_name: '	Nurullah	', last_name: ' 	Geckil	', date_of_birth: Date.parse('	1998-06-01	'), weight:	54	, gender:	FALSE	, fights_won:	1	, fights_lost:	1	, fights_drawn:	0	, club_id:	19	},
{ first_name: '	Enes	', last_name: ' 	Demirhan	', date_of_birth: Date.parse('	1998-07-01	'), weight:	63	, gender:	FALSE	, fights_won:	1	, fights_lost:	2	, fights_drawn:	0	, club_id:	19	},
{ first_name: '	Yasin	', last_name: ' 	Eskier	', date_of_birth: Date.parse('	1998-01-01	'), weight:	63	, gender:	FALSE	, fights_won:	3	, fights_lost:	1	, fights_drawn:	0	, club_id:	19	},
{ first_name: '	David	', last_name: ' 	Ohlsen	', date_of_birth: Date.parse('	1986-12-01	'), weight:	75	, gender:	FALSE	, fights_won:	2	, fights_lost:	0	, fights_drawn:	0	, club_id:	19	},
{ first_name: '	Hassan	', last_name: ' 	Moussa	', date_of_birth: Date.parse('	1989-06-01	'), weight:	81	, gender:	FALSE	, fights_won:	3	, fights_lost:	1	, fights_drawn:	0	, club_id:	19	},
{ first_name: '	Henry	', last_name: ' 	Sieg	', date_of_birth: Date.parse('	1990-01-01	'), weight:	98	, gender:	FALSE	, fights_won:	2	, fights_lost:	1	, fights_drawn:	0	, club_id:	19	},
																		
{ first_name: '	Sophia	', last_name: ' 	Fielitz	', date_of_birth: Date.parse('	2001-05-01	'), weight:	60	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	3	},
{ first_name: '	Debby	', last_name: ' 	Klauk	', date_of_birth: Date.parse('	1998-04-01	'), weight:	62	, gender:	TRUE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	3	},
{ first_name: '	Tarik	', last_name: ' 	Genc	', date_of_birth: Date.parse('	2003-01-01	'), weight:	40	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	3	},
{ first_name: '	Arthur	', last_name: ' 	Brendl	', date_of_birth: Date.parse('	2001-10-01	'), weight:	45	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	3	},
{ first_name: '	Drago	', last_name: ' 	Schade	', date_of_birth: Date.parse('	2001-01-01	'), weight:	56	, gender:	FALSE	, fights_won:	5	, fights_lost:	6	, fights_drawn:	0	, club_id:	3	},
{ first_name: '	Bülent	', last_name: ' 	Tutal	', date_of_birth: Date.parse('	2001-01-01	'), weight:	64	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	3	},
																		
{ first_name: '	Lale	', last_name: ' 	Petrovic	', date_of_birth: Date.parse('	1999-08-01	'), weight:	51	, gender:	TRUE	, fights_won:	0	, fights_lost:	1	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Daev	', last_name: ' 	Tamirlan	', date_of_birth: Date.parse('	2002-06-01	'), weight:	38	, gender:	FALSE	, fights_won:	2	, fights_lost:	6	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Adam	', last_name: ' 	Tsechoev	', date_of_birth: Date.parse('	2001-09-01	'), weight:	38	, gender:	FALSE	, fights_won:	2	, fights_lost:	4	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Eric	', last_name: ' 	Ebert	', date_of_birth: Date.parse('	2001-01-01	'), weight:	59	, gender:	FALSE	, fights_won:	1	, fights_lost:	2	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Bondin	', last_name: ' 	Aziev	', date_of_birth: Date.parse('	2000-12-01	'), weight:	32	, gender:	FALSE	, fights_won:	0	, fights_lost:	2	, fights_drawn:	1	, club_id:	20	},
{ first_name: '	Attila	', last_name: ' 	Sahin	', date_of_birth: Date.parse('	2000-09-01	'), weight:	38	, gender:	FALSE	, fights_won:	3	, fights_lost:	10	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Gino	', last_name: ' 	Tiefenbach	', date_of_birth: Date.parse('	2000-09-01	'), weight:	46	, gender:	FALSE	, fights_won:	0	, fights_lost:	3	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Ivan	', last_name: ' 	Volodko	', date_of_birth: Date.parse('	1999-08-01	'), weight:	61	, gender:	FALSE	, fights_won:	0	, fights_lost:	2	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Islam	', last_name: ' 	Demelhanov	', date_of_birth: Date.parse('	1998-05-01	'), weight:	56	, gender:	FALSE	, fights_won:	3	, fights_lost:	3	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Tobias	', last_name: ' 	Heymel	', date_of_birth: Date.parse('	1998-09-01	'), weight:	60	, gender:	FALSE	, fights_won:	1	, fights_lost:	5	, fights_drawn:	1	, club_id:	20	},
{ first_name: '	Isa	', last_name: ' 	Binchaev	', date_of_birth: Date.parse('	1997-07-01	'), weight:	63	, gender:	FALSE	, fights_won:	1	, fights_lost:	2	, fights_drawn:	0	, club_id:	20	},
{ first_name: '	Irkan	', last_name: ' 	Özhan	', date_of_birth: Date.parse('	1988-12-01	'), weight:	83	, gender:	FALSE	, fights_won:	0	, fights_lost:	1	, fights_drawn:	0	, club_id:	20	},
																		
{ first_name: '	Bilal	', last_name: ' 	Dashaev	', date_of_birth: Date.parse('	2003-09-01	'), weight:	34	, gender:	FALSE	, fights_won:	0	, fights_lost:	0	, fights_drawn:	0	, club_id:	21	},
{ first_name: '	Ismail	', last_name: ' 	Dashaev	', date_of_birth: Date.parse('	2000-02-01	'), weight:	48	, gender:	FALSE	, fights_won:	3	, fights_lost:	0	, fights_drawn:	0	, club_id:	21	},
#{ first_name: '	Carlos	', last_name: ' 	Chari	', date_of_birth: Date.parse('	1998-01-01	'), weight:	57	, gender:	FALSE	, fights_won:	2	, fights_lost:	6	, fights_drawn:	0	, club_id:	21	},
{ first_name: '	Luckas	', last_name: ' 	Zickrow	', date_of_birth: Date.parse('	1998-11-01	'), weight:	60	, gender:	FALSE	, fights_won:	1	, fights_lost:	1	, fights_drawn:	0	, club_id:	21	},
{ first_name: '	Benjamin	', last_name: ' 	Masa	', date_of_birth: Date.parse('	1998-06-01	'), weight:	70	, gender:	FALSE	, fights_won:	3	, fights_lost:	4	, fights_drawn:	0	, club_id:	21	},
{ first_name: '	Marc	', last_name: ' 	Moul	', date_of_birth: Date.parse('	1998-05-01	'), weight:	70	, gender:	FALSE	, fights_won:	13	, fights_lost:	9	, fights_drawn:	0	, club_id:	21	},
{ first_name: '	Issa	', last_name: ' 	Yasine	', date_of_birth: Date.parse('	1997-07-01	'), weight:	69	, gender:	FALSE	, fights_won:	3	, fights_lost:	0	, fights_drawn:	0	, club_id:	21	},
{ first_name: '	Cengiz	', last_name: ' 	Cayir	', date_of_birth: Date.parse('	1995-05-01	'), weight:	69	, gender:	FALSE	, fights_won:	12	, fights_lost:	5	, fights_drawn:	1	, club_id:	21	},
{ first_name: '	Alexander	', last_name: ' 	Wozniak	', date_of_birth: Date.parse('	1987-06-01	'), weight:	75	, gender:	FALSE	, fights_won:	6	, fights_lost:	4	, fights_drawn:	0	, club_id:	21	},
{ first_name: '	Kendal	', last_name: ' 	Qicco	', date_of_birth: Date.parse('	1993-01-01	'), weight:	91	, gender:	FALSE	, fights_won:	8	, fights_lost:	5	, fights_drawn:	1	, club_id:	21	}

])
