require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe BoxersController do

  # This should return the minimal set of attributes required to create a valid
  # Boxer. As you add validations to Boxer, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "first_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # BoxersController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all boxers as @boxers" do
      boxer = Boxer.create! valid_attributes
      get :index, {}, valid_session
      assigns(:boxers).should eq([boxer])
    end
  end

  describe "GET show" do
    it "assigns the requested boxer as @boxer" do
      boxer = Boxer.create! valid_attributes
      get :show, {:id => boxer.to_param}, valid_session
      assigns(:boxer).should eq(boxer)
    end
  end

  describe "GET new" do
    it "assigns a new boxer as @boxer" do
      get :new, {}, valid_session
      assigns(:boxer).should be_a_new(Boxer)
    end
  end

  describe "GET edit" do
    it "assigns the requested boxer as @boxer" do
      boxer = Boxer.create! valid_attributes
      get :edit, {:id => boxer.to_param}, valid_session
      assigns(:boxer).should eq(boxer)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Boxer" do
        expect {
          post :create, {:boxer => valid_attributes}, valid_session
        }.to change(Boxer, :count).by(1)
      end

      it "assigns a newly created boxer as @boxer" do
        post :create, {:boxer => valid_attributes}, valid_session
        assigns(:boxer).should be_a(Boxer)
        assigns(:boxer).should be_persisted
      end

      it "redirects to the created boxer" do
        post :create, {:boxer => valid_attributes}, valid_session
        response.should redirect_to(Boxer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved boxer as @boxer" do
        # Trigger the behavior that occurs when invalid params are submitted
        Boxer.any_instance.stub(:save).and_return(false)
        post :create, {:boxer => { "first_name" => "invalid value" }}, valid_session
        assigns(:boxer).should be_a_new(Boxer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Boxer.any_instance.stub(:save).and_return(false)
        post :create, {:boxer => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested boxer" do
        boxer = Boxer.create! valid_attributes
        # Assuming there are no other boxers in the database, this
        # specifies that the Boxer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Boxer.any_instance.should_receive(:update).with({ "first_name" => "MyString" })
        put :update, {:id => boxer.to_param, :boxer => { "first_name" => "MyString" }}, valid_session
      end

      it "assigns the requested boxer as @boxer" do
        boxer = Boxer.create! valid_attributes
        put :update, {:id => boxer.to_param, :boxer => valid_attributes}, valid_session
        assigns(:boxer).should eq(boxer)
      end

      it "redirects to the boxer" do
        boxer = Boxer.create! valid_attributes
        put :update, {:id => boxer.to_param, :boxer => valid_attributes}, valid_session
        response.should redirect_to(boxer)
      end
    end

    describe "with invalid params" do
      it "assigns the boxer as @boxer" do
        boxer = Boxer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Boxer.any_instance.stub(:save).and_return(false)
        put :update, {:id => boxer.to_param, :boxer => { "first_name" => "invalid value" }}, valid_session
        assigns(:boxer).should eq(boxer)
      end

      it "re-renders the 'edit' template" do
        boxer = Boxer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Boxer.any_instance.stub(:save).and_return(false)
        put :update, {:id => boxer.to_param, :boxer => { "first_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested boxer" do
      boxer = Boxer.create! valid_attributes
      expect {
        delete :destroy, {:id => boxer.to_param}, valid_session
      }.to change(Boxer, :count).by(-1)
    end

    it "redirects to the boxers list" do
      boxer = Boxer.create! valid_attributes
      delete :destroy, {:id => boxer.to_param}, valid_session
      response.should redirect_to(boxers_url)
    end
  end

end
